config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  match "/random_book", to: "books#random_book", via: :get
  resources :books
  resources :statics

  root 'statics#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	 has_attached_file :cover
	 do_not_validate_attachment_file_type :cover
end

app/models/static.rb
class Static < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :update_sanitized_params, if: :devise_controller?

    def update_sanitized_params
        devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:first_name, :last_name, :site_link, :password, :password_confirmation, :email)}
    end

    def after_sign_in_path_for(user)         
    	users_path
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def random_book
    books = Book.all
    @book = books.sample
    redirect_to book_path(@book)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_first_name, :author_last_name, :number_of_pages, :is_science_fiction, :is_satire, :is_drama, :is_action, :is_adventure, :is_romance, :is_mystery, :is_horror, :is_children, :is_science, :is_history, :is_math, :is_anthology, :is_poetry, :is_comic, :is_diary, :is_series, :is_bio_autobio, :is_fantasy, :is_dragon, :is_fairy_tale, :cover)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_action :set_static, only: [:show, :edit, :update, :destroy]

  # GET /statics
  # GET /statics.json
  def index
    @statics = Static.all
  end

  # GET /statics/1
  # GET /statics/1.json
  def show
  end

  # GET /statics/new
  def new
    @static = Static.new
  end

  # GET /statics/1/edit
  def edit
  end

  # POST /statics
  # POST /statics.json
  def create
    @static = Static.new(static_params)

    respond_to do |format|
      if @static.save
        format.html { redirect_to @static, notice: 'Static was successfully created.' }
        format.json { render :show, status: :created, location: @static }
      else
        format.html { render :new }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statics/1
  # PATCH/PUT /statics/1.json
  def update
    respond_to do |format|
      if @static.update(static_params)
        format.html { redirect_to @static, notice: 'Static was successfully updated.' }
        format.json { render :show, status: :ok, location: @static }
      else
        format.html { render :edit }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statics/1
  # DELETE /statics/1.json
  def destroy
    @static.destroy
    respond_to do |format|
      format.html { redirect_to statics_url, notice: 'Static was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static
      @static = Static.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_params
      params[:static]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :site_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :cover %><br>
    <%= f.file_field :cover %>
  </div>
  <div class="field">
    <%= f.label :author_first_name %><br>
    <%= f.text_field :author_first_name %>
  </div>
  <div class="field">
    <%= f.label :author_last_name %><br>
    <%= f.text_field :author_last_name %>
  </div>
  <div class="field">
    <%= f.label :number_of_pages %><br>
    <%= f.number_field :number_of_pages %>
  </div>
  <div class="field">
    <%= f.label :is_science_fiction %><br>
    <%= f.check_box :is_science_fiction %>
  </div>
  <div class="field">
    <%= f.label :is_satire %><br>
    <%= f.check_box :is_satire %>
  </div>
  <div class="field">
    <%= f.label :is_drama %><br>
    <%= f.check_box :is_drama %>
  </div>
  <div class="field">
    <%= f.label :is_action %><br>
    <%= f.check_box :is_action %>
  </div>
  <div class="field">
    <%= f.label :is_adventure %><br>
    <%= f.check_box :is_adventure %>
  </div>
  <div class="field">
    <%= f.label :is_romance %><br>
    <%= f.check_box :is_romance %>
  </div>
  <div class="field">
    <%= f.label :is_mystery %><br>
    <%= f.check_box :is_mystery %>
  </div>
  <div class="field">
    <%= f.label :is_horror %><br>
    <%= f.check_box :is_horror %>
  </div>
  <div class="field">
    <%= f.label :is_children %><br>
    <%= f.check_box :is_children %>
  </div>
  <div class="field">
    <%= f.label :is_science %><br>
    <%= f.check_box :is_science %>
  </div>
  <div class="field">
    <%= f.label :is_history %><br>
    <%= f.check_box :is_history %>
  </div>
  <div class="field">
    <%= f.label :is_math %><br>
    <%= f.check_box :is_math %>
  </div>
  <div class="field">
    <%= f.label :is_anthology %><br>
    <%= f.check_box :is_anthology %>
  </div>
  <div class="field">
    <%= f.label :is_poetry %><br>
    <%= f.check_box :is_poetry %>
  </div>
  <div class="field">
    <%= f.label :is_comic %><br>
    <%= f.check_box :is_comic %>
  </div>
  <div class="field">
    <%= f.label :is_diary %><br>
    <%= f.check_box :is_diary %>
  </div>
  <div class="field">
    <%= f.label :is_series %><br>
    <%= f.check_box :is_series %>
  </div>
  <div class="field">
    <%= f.label :is_bio_autobio %><br>
    <%= f.check_box :is_bio_autobio %>
  </div>
  <div class="field">
    <%= f.label :is_fantasy %><br>
    <%= f.check_box :is_fantasy %>
  </div>
  <div class="field">
    <%= f.label :is_dragon %><br>
    <%= f.check_box :is_dragon %>
  </div>
  <div class="field">
    <%= f.label :is_fairy_tale %><br>
    <%= f.check_box :is_fairy_tale %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Author first name</th>
          <th>Author last name</th>
          <th>Number of pages</th>
          <th> science fiction</th>
          <th> top 100</th>
          <th> satire</th>
          <th> drama</th>
          <th> action</th>
          <th> adventure</th>
          <th> romance</th>
          <th> mystery</th>
          <th> horror</th>
          <th> children</th>
          <th> science</th>
          <th> history</th>
          <th> math</th>
          <th> anthology</th>
          <th> poetry</th>
          <th> comic</th>
          <th> diary</th>
          <th> series</th>
          <th> bio autobio</th>
          <th> fantasy</th>
          <th> dragon</th>
          <th> fairy tale</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    <tbody>

    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author_first_name %></td>
        <td><%= book.author_last_name %></td>
        <td><%= book.number_of_pages %></td>
        <td><%= book.is_science_fiction %></td>
        <td><%= book.is_satire %></td>
        <td><%= book.is_drama %></td>
        <td><%= book.is_action %></td>
        <td><%= book.is_adventure %></td>
        <td><%= book.is_romance %></td>
        <td><%= book.is_mystery %></td>
        <td><%= book.is_horror %></td>
        <td><%= book.is_children %></td>
        <td><%= book.is_science %></td>
        <td><%= book.is_history %></td>
        <td><%= book.is_math %></td>
        <td><%= book.is_anthology %></td>
        <td><%= book.is_poetry %></td>
        <td><%= book.is_comic %></td>
        <td><%= book.is_diary %></td>
        <td><%= book.is_series %></td>
        <td><%= book.is_bio_autobio %></td>
        <td><%= book.is_fantasy %></td>
        <td><%= book.is_dragon %></td>
        <td><%= book.is_fairy_tale %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-5 col-md-offset-1">

    <p>
      <strong>Title:</strong>
      <%= @book.title %>
    </p>

    <p>
      <strong>Author first name:</strong>
      <%= @book.author_first_name %>
    </p>

    <p>
      <strong>Author last name:</strong>
      <%= @book.author_last_name %>
    </p>

    <p>
      <strong>Number of pages:</strong>
      <%= @book.number_of_pages %>
    </p>

    <p>
      <strong>Is science fiction:</strong>
      <%= @book.is_science_fiction %>
    </p>

    <p>
      <strong>Is satire:</strong>
      <%= @book.is_satire %>
    </p>

    <p>
      <strong>Is drama:</strong>
      <%= @book.is_drama %>
    </p>

    <p>
      <strong>Is action:</strong>
      <%= @book.is_action %>
    </p>

    <p>
      <strong>Is adventure:</strong>
      <%= @book.is_adventure %>
    </p>

    <p>
      <strong>Is romance:</strong>
      <%= @book.is_romance %>
    </p>

    <p>
      <strong>Is mystery:</strong>
      <%= @book.is_mystery %>
    </p>

    <p>
      <strong>Is horror:</strong>
      <%= @book.is_horror %>
    </p>

    <p>
      <strong>Is children:</strong>
      <%= @book.is_children %>
    </p>

    <p>
      <strong>Is science:</strong>
      <%= @book.is_science %>
    </p>

    <p>
      <strong>Is history:</strong>
      <%= @book.is_history %>
    </p>

    <p>
      <strong>Is math:</strong>
      <%= @book.is_math %>
    </p>

    <p>
      <strong>Is anthology:</strong>
      <%= @book.is_anthology %>
    </p>

    <p>
      <strong>Is poetry:</strong>
      <%= @book.is_poetry %>
    </p>

    <p>
      <strong>Is comic:</strong>
      <%= @book.is_comic %>
    </p>

    <p>
      <strong>Is diary:</strong>
      <%= @book.is_diary %>
    </p>

    <p>
      <strong>Is series:</strong>
      <%= @book.is_series %>
    </p>

    <p>
      <strong>Is bio autobio:</strong>
      <%= @book.is_bio_autobio %>
    </p>

    <p>
      <strong>Is fantasy:</strong>
      <%= @book.is_fantasy %>
    </p>

    <p>
      <strong>Is dragon:</strong>
      <%= @book.is_dragon %>
    </p>

    <p>
      <strong>Is fairy tale:</strong>
      <%= @book.is_fairy_tale %>
    </p>
  </div>
  <div class="col-md-5">
    <% if @book.cover.exists? %>
      <%= image_tag @book.cover.url %>
    <% end %>
  </div>
</div>

    <%= link_to 'Edit', edit_book_path(@book) %> |
    <%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReadNext</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
	 <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">NextRead</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="#">My favorite books<span class="sr-only">(current)</span></a></li>
          <li><a href="#">Reselect topics</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Options <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="<%= books_path %>">Full list of books </a></li>
              <li><a href="#">Contact</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Thank you Jeff</a></li>
              <li role="separator" class="divider"></li>
              <% if signed_in? %>
                <li><a href="<%= user_path(current_user) %>">your account</a></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>



<%= yield %>

</body>
</html>

app/views/statics/_form.html.erb
<%= form_for(@static) do |f| %>
  <% if @static.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static.errors.count, "error") %> prohibited this static from being saved:</h2>

      <ul>
      <% @static.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statics/edit.html.erb
<h1>Editing Static</h1>

<%= render 'form' %>

<%= link_to 'Show', @static %> |
<%= link_to 'Back', statics_path %>

app/views/statics/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-7 col-md-offset-1">
      <div class="jumbotron-text">
        <div class="background-color"> 
          <div class="container">
            <div class="title-color">
              <div class="gap"> 
                <h1>Recommend me a book!</h1>
                <br> 
                <div><a class="btn btn-warning btn-lg" href="<%= random_book_path %>">Suggest a Random Book</a></div>   
                  <div>
                  </div>
                <br>    
                <div><button class="btn btn-success btn-lg">Let me narrow my search</button></div>
                  <div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <img src="http://i.imgur.com/719iUzG.png" style="width: 140%; height: 130%">
    </div>
  </div>
</div>

app/views/statics/new.html.erb
<h1>New Static</h1>

<%= render 'form' %>

<%= link_to 'Back', statics_path %>

app/views/statics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_path(@static) %> |
<%= link_to 'Back', statics_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :site_link %><br>
    <%= f.text_field :site_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Site link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.site_link %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Site link:</strong>
  <%= @user.site_link %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>